param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "C:\Program Files\IAR Systems\Embedded Workbench 9.1\common\bin\cspybat" -f "C:\Users\user\Desktop\TMP\급속 펌웨어\Sinexcel Module\JC-9932-100-CU07_Win_ver급속_F\Project\STM32F105\EWARM_v7\settings\JC-9642-300-012.SINEXCEL_40kW.general.xcl" --backend -f "C:\Users\user\Desktop\TMP\급속 펌웨어\Sinexcel Module\JC-9932-100-CU07_Win_ver급속_F\Project\STM32F105\EWARM_v7\settings\JC-9642-300-012.SINEXCEL_40kW.driver.xcl" 
}
else
{
& "C:\Program Files\IAR Systems\Embedded Workbench 9.1\common\bin\cspybat" -f "C:\Users\user\Desktop\TMP\급속 펌웨어\Sinexcel Module\JC-9932-100-CU07_Win_ver급속_F\Project\STM32F105\EWARM_v7\settings\JC-9642-300-012.SINEXCEL_40kW.general.xcl" --debug_file=$debugfile --backend -f "C:\Users\user\Desktop\TMP\급속 펌웨어\Sinexcel Module\JC-9932-100-CU07_Win_ver급속_F\Project\STM32F105\EWARM_v7\settings\JC-9642-300-012.SINEXCEL_40kW.driver.xcl" 
}
